version: '3.9'

services:

#  postgres:
#    image: postgres
#    container_name: postgres
#    restart: unless-stopped
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      PGDATA: /data/postgres
#    volumes:
#      - postgres:/data/postgres
#      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
#    ports:
#      - '5432:5432'

  api-service:
    container_name: api-service
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - backend

  minio:
    image: bitnami/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin@2024
    volumes:
      - minio_data:/bitnami/minio/data
      - minio_config:/opt/bitnami/minio/config
    ports:
      - '9000:9000'
      - '9001:9001'
    command: minio server /bitnami/minio/data --console-address ":9001"

  redis:
    image: redis:6.2-alpine
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB;FLUSHALL
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres:
  minio_data:
  minio_config:
